theme: jekyll-theme-tactile
title: Abdulla Saqui
description: Web Solution Provider - Bookmark this page for latest update!
show_downloads: false
navigation:
  - text: "Home"
    link: "/"
    icon: "🏠"
